config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  namespace :grocery do
    get 'weekly'
    get 'daily'
    get 'custom'
  end

  get 'location', to: 'pages#location'
  get 'task_details', to: 'pages#task_details'
  get 'cart', to: 'pages#cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grocery_controller.rb
class GroceryController < ApplicationController
  protect_from_forgery with: :exception

  def weekly
    @day_start = Date.today.monday.next_week
  end

  def daily
  end

  def custom
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery with: :exception

  def home
  end

  def cart
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :contact_no, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :contact_no, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  INGREDIENTS = [
    'Apple',
    'Apricot',
    'Asparagus',
    'Aubergine',
    'Avocado',
    'Banana',
    'Beetroot',
    'Black-eye bean',
    'Broad bean',
    'Broccoli',
    'Brussels sprout',
    'Butternut Squash',
    'Carrot',
    'Cherry',
    'Clementine',
    'Courgette',
    'Date',
    'Elderberry',
    'Endive',
    'Fennel',
    'Fig',
    'Garlic',
    'Grape',
    'Green bean',
    'Guava',
    'Haricot bean',
    'Honeydew melon',
    'Iceberg lettuce',
    'Jerusalem artichoke',
    'Kiwi fruit',
    'Leek',
    'Lemon',
    'Mango',
    'Melon',
    'Mushroom',
    'Nectarine',
    'Nut',
    'Olive',
    'Orange',
    'Pea',
    'Peanut',
    'Pear',
    'Pepper',
    'Pineapple',
    'Pumpkin',
    'Quince',
    'Radish',
    'Raisin',
    'Rhubarb',
    'Satsuma',
    'Strawberry',
    'Sweet potato',
    'Tomato',
    'Turnip',
    'Ugli fruit',
    'Victoria plum',
    'Vine leaf',
    'Watercress',
    'Watermelon',
    'Yam',
    'Zucchini'
  ]



  MEALS = [
    { name: 'Meatloaf', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/4/13/0/GC_good-eats-meatloaf_s4x3.jpg.rend.hgtvcom.616.462.suffix/1380061114628.jpeg', price: 100 },
    { name: 'Honey Baked Chicken', img_url: 'http://foodell.com/images/recipes/Honey_soy_chicken.jpg', price: 150  },
    { name: 'Salisbury Steak', img_url: 'http://cincyshopper.com/wp-content/uploads/2015/10/Simple-Salisbury-Steak-11.jpg', price: 200 },
    { name: 'Taco Salad', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/9/4/0/FNM_100112-Almost-Famous-Steak-Taco-Salad-Recipe_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371609332863.jpeg', price: 93 },
    { name: 'Chicken Fajitas', img_url: 'https://www.ndtv.com/cooks/images/chicken-fajitas.jpg', price: 100 },
    { name: 'Corn Chowder', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/9/29/0/ig1a13_corn_chowder.jpg.rend.hgtvcom.616.462.suffix/1485462146643.jpeg', price: 86 },
    { name: 'Cheeseburger Soup', img_url: 'https://cdn2.tmbi.com/TOH/Images/Photos/37/300x300/Cheeseburger-Soup_EXPS_SBZ17_2832_B10_21_1b.jpg', price: 132 },
    { name: 'Chicken Caesar Salad', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/3/3/0/FNM_040110-W-N-Dinners-015_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371591380107.jpeg', price: 112 },
    { name: 'Spaghetti', img_url: 'http://www.simplyrecipes.com/wp-content/uploads/2006/09/italian-sausage-spaghetti-horiz-640.jpg', price: 123 },
    { name: 'Pizza', img_url: 'https://cdn.modpizza.com/wp-content/uploads/2016/11/mod-pizza-mad-dog-e1479167997381.png', price: 122 },
    { name: 'Calzones', img_url: 'http://s3.amazonaws.com/finecooking.s3.tauntonclud.com/app/uploads/2017/04/18190744/051092070-01-calzone-recipe-main.jpg', price: 99 },
    { name: 'Stuffed Shells & Peppers', img_url: 'http://4.bp.blogspot.com/-gopxeQfK158/UyJO8Xbk6MI/AAAAAAAAFWk/q4aPuxvPnrs/s1600/Sausage-Stuffed-Shells-3.jpg', price: 135 },
    { name: 'Chicken Divan', img_url: 'https://images-gmi-pmc.edge-generalmills.com/63c052f9-6b0c-4291-9d4f-f0aa4cff4b0c.jpg', price: 111 },
    { name: 'Quiche', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2015/8/4/1/VB0102H_Quiche-Valerie_s4x3.jpg.rend.hgtvcom.616.462.suffix/1438736464664.jpeg', price: 153 },
    { name: 'White Garlic Lasagna', img_url: 'http://tastykitchen.com/wp-content/uploads/2013/01/Tasty-Kitchen-Blog-White-Cheese-and-Chicken-Lasagna.jpg', price: 90 },
    { name: 'Macaroni & Cheese', img_url: 'https://lh6.googleusercontent.com/-zgsC9661HqE/T84vD55kg3I/AAAAAAAAHEc/ozqe4On72sw/s640/Miracle+Mac+front.jpg', price: 93 },
    { name: 'Grilled Chicken', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/4/14/2/FNM060109WE0421_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371589415669.jpeg', price: 78 },
    { name: 'Burgers', img_url: 'https://images.fastcompany.net/image/upload/w_596,c_limit,q_auto:best,f_auto,fl_lossy/wp-cms/uploads/2017/06/i-1-sonic-burger.jpg', price: 135 },
    { name: 'Enchiladas', img_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/10/1/0/WU0308H_simple-perfect-enchiladas_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382541970364.jpeg', price: 123 },
    { name: 'Mexican Lasagna', img_url: 'https://images-gmi-pmc.edge-generalmills.com/4d613857-4401-44c7-aae6-c50d16359755.jpg', price: 89 }
  ].freeze

  def random_meal(size)
    MEALS.sample(size)
  end

  def ingredient_list
    INGREDIENTS
  end
end

app/helpers/cdn_helper.rb
module CdnHelper

  BOOTSTRAP_VERSION = '3.3.7'
  JQUERY_VERSION = '3.2.1'
  ANGULR_VERSION = '1.6.4'

  def use_cdn?
    true
  end

  def bootstrap_css_settings
    {
      media: 'all',
      integrity: 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u',
      crossorigin: 'anonymous'
    }
  end

  def bootstrap_js_settings
    {
      integrity: 'sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa',
      crossorigin: 'anonymous'
    }
  end

  def bootstrap_cdn_url(type)
    'https://maxcdn.bootstrapcdn.com/bootstrap/' + BOOTSTRAP_VERSION + '/' + type + '/bootstrap.min.' + type
  end

  def jquery_cdn_url
    'https://ajax.googleapis.com/ajax/libs/jquery/' + JQUERY_VERSION + '/jquery.min.js'
  end

  def angular_cdn_url
    'https://ajax.googleapis.com/ajax/libs/angularjs/' + ANGULR_VERSION + '/angular.min.js'
  end
end

app/helpers/date_helper.rb
module DateHelper

  def header_format(date)
    date.strftime('%b %-d, %Y - %a')
  end
end

app/views/grocery/custom.html.haml
.wrapper#customContent{ng: { controller: 'CustomCtrl'}}
  %section#form-section.section-padding
    .container
      .row
        .header-section
          %h2.pull-left
            Order by Ingredients
          .pull-right.curateNavs
            %ul.nav.nav-tabs.navbar-right
              %li.clickable.active
                %a Custom
              %li.clickable.nav-item
                = link_to 'Weekly', grocery_weekly_path
              %li.clickable.nav-item
                = link_to 'Daily', grocery_daily_path
      .row
        .table-responsive
          %table.table.table-bordered.table-striped.table-fixed
            %thead
              %tr
                %th Image
                %th Product
                %th Unit Price
                %th Quantity
                %th
            %tbody
              - ingredient_list.each do |ingredient|
                %tr
                  %td
                    .in
                      = image_tag "ingredients/#{ingredient}.jpg", width: 50, height: 50
                  %td=ingredient
                  %td= 'PHP ' + rand(50..150).to_s + '/kg'
                  %td
                    %div.input-group.input-group-sm.top10
                      %input.form-control{type: 'number', value: 1}
                      %span.input-group-addon kg
                  %td
                    %button.btn.btn-default
                      Add To Cart
      .row
        .col-md-6
          Total:
          %span PHP 600.00
        .col-md-6
          = link_to 'Checkout', cart_path, class: 'btn btn-green btn-primary pull-right'

app/views/grocery/daily.html.haml
.wrapper{ng: { controller: 'DailyCtrl'}}
  %section#form-section.section-padding
    .container
      .row
        .header-section
          %h2.pull-left
            Choose Your Meal for a Day
          .pull-right.curateNavs
            %ul.nav.nav-tabs.navbar-right
              %li.clickable
                = link_to 'Custom', grocery_custom_path
              %li.clickable.nav-item
                = link_to 'Weekly', grocery_weekly_path
              %li.clickable.nav-item.active
                %a Daily
      .row
        %table.table.table-bordered
          %tr
            %th.text-center Meal 1
            %th.text-center Meal 2
            %th.text-center Meal 3

          %tr
            %td.td-meal#tdMeal1{data: {toggle: 'popover', trigger: 'hover', container: 'body', html: true}}
              - meal = random_meal(1).first
              %button.btn.btn-green.btn-block.btn-meal-md#btnMeal1{data: {toggle: '', target: '#searchMealModal'}}
                = meal[:name]

              .meal-info.text-center.top10
                .avatar.meal-icon-md
                  = image_tag meal[:img_url], width: 93, height: 93, class: 'avatar'
                %span
                  PHP
                  = meal[:price]
              %div.input-group.input-group-sm.top10
                %input.form-control{type: 'number', value: 1}
                %span.input-group-addon servings




            %td.td-meal#tdMeal2{data: {toggle: 'popover', trigger: 'hover', container: 'body', html: true}}
              - meal = random_meal(1).first
              %button.btn.btn-green.btn-block.btn-meal-md#btnMeal2{data: {toggle: '', target: '#searchMealModal'}}
                = meal[:name]

              .meal-info.text-center.top10
                .avatar.meal-icon-md
                  = image_tag meal[:img_url], width: 93, height: 93, class: 'avatar'
                %span
                  PHP
                  = meal[:price]
              %div.input-group.input-group-sm.top10
                %input.form-control{type: 'number', value: 1}
                %span.input-group-addon servings

            %td.td-meal#tdMeal3{data: {toggle: 'popover', trigger: 'hover', container: 'body', html: true}}
              - meal = random_meal(1).first
              %button.btn.btn-green.btn-block.btn-meal-md#btnMeal3{data: {toggle: '', target: '#searchMealModal'}}
                = meal[:name]

              .meal-info.text-center.top10
                .avatar.meal-icon-md
                  = image_tag meal[:img_url], width: 93, height: 93, class: 'avatar'
                %span
                  PHP
                  = meal[:price]
              %div.input-group.input-group-sm.top10
                %input.form-control{type: 'number', value: 1}
                %span.input-group-addon servings
      .row
        .col-md-6
          Total:
          %span PHP 600.00
        .col-md-6
          = link_to 'Checkout', cart_path, class: 'btn btn-green btn-primary pull-right'
#searchMealModal.modal.fade{role: 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}} &times;
        %h4.modal-title Set Meal
      .modal-body
        .input-group
          %input.form-control{type: 'text', placeholder: 'Search Meal'}
          %span.input-group-addon
            %i.fa.fa-search
        - meals = random_meal(6)
        .list-group.top5
          - meals.each do |meal|
            %a.list-group-item{href: 'javascript:;', data: {dismiss: 'modal'}}
              .avatar.meal-icon
                = image_tag meal[:img_url], width: 53, height: 53, class: 'avatar'
              = meal[:name].to_s + ' - PHP ' + meal[:price].to_s

-#popover
.row#popoverTemplate.hide
  .header-section
    %h4#mealName
  %ul.nav.nav-tabs
    %li.clickable.active
      %a#ingredientsTab{data: {toggle: 'tab'}, href: '.ingredients'} Ingredients
    %li.clickable.nav-item
      %a#directionsTab{data: {toggle: 'tab'}, href: '.directions'} Directions
  .tab-content
    #ingredients.tab-pane.in.active.ingredients
      %ul.top5{style: 'list-style-type: circle'}
        %li 2 tablespoons extra-virgin olive oil
        %li 1 small onion, chopped
        %li 1 carrot, chopped
        %li 1 shallot, minced
        %li 3 1/2 ounces prosciutto, chopped
        %li 11 ounces ground pork
        %li 11 ounces ground beef
        %li 1 teaspoon ground nutmeg
        %li 1/2 teaspoon ground cinnamon
        %li salt to taste
    #directions.tab-pane.directions
      %ul.top5{style: 'list-style-type: circle'}
        %li Heat olive oil in a saucepan over medium heat; cook and stir onion, carrot, shallot, and prosciutto until onion is translucent and prosciutto releases some fat, about 10 minutes. Add pork and beef; season with 1 teaspoon nutmeg, cinnamon, and salt to taste. Cook and stir over medium-high heat until browned and crumbly, about 10 minutes.
        %li Pour red wine over meat mixture; increase heat and cook until wine evaporates, about 3 minutes. Add tomatoes and mix well; bring to a boil, cover, reduce heat, and simmer, stirring occasionally, until tomatoes break down and flavors of Bolognese sauce have combined, 1 1/2 to 2 hours.
        %li Melt butter in a saucepan over medium-low heat; add flour. Whisk vigorously until mixture is smooth. Pour in milk and cook, stirring occasionally, over medium heat until white sauce thickens enough to cover the back of a spoon, about 10 minutes; season with 1/2 teaspoon nutmeg, salt, and pepper.
        %li Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in the boiling water, stirring occasionally until tender yet firm to the bite, about 8 minutes. Drain and run under cold water to stop the cooking process. Lay noodles on a clean towel and pat dry.
        %li Pour a ladleful of Bolognese sauce and a ladleful of white sauce over the bottom of a 9x13-inch baking dish; top with 3 or 4 lasagna noodles. Cover noodles with 1/3 of the white sauce and 1/3 of the Bolognese sauce. Sprinkle some of the Parmesan cheese on top; cover with lasagna noodles. Repeat layers, ending with white sauce and Parmesan cheese.
        %li Bake in the preheated oven until bubbling and top is golden brown, 30 to 40 minutes. Let stand 3 to 4 minutes before slicing.

app/views/grocery/weekly.html.haml
.wrapper#weeklyContent{ng: { controller: 'WeeklyCtrl'}}
  %section#form-section.section-padding
    .container
      .row
        .header-section
          %h2.pull-left
            Plan your meals
          .pull-right.curateNavs
            %ul.nav.nav-tabs.navbar-right
              %li.clickable
                = link_to 'Custom', grocery_custom_path
              %li.clickable.nav-item.active
                %a Weekly
              %li.clickable.nav-item
                = link_to 'Daily', grocery_daily_path
      .row
        %table.table.table-bordered
          %tr
            - 7.times do |i|
              %th.text-center
                = header_format(@day_start + i.days)
          - 3.times do |x|
            %tr
              - 7.times do |i|
                - meal = random_meal(1).first
                %td.td-meal{data: {toggle: 'popover', trigger: 'hover', container: 'body', html: true, id: (x*7+i).to_s}}
                  %button.btn.btn-green.btn-block.btn-meal{data: {toggle: '', target: '#searchMealModal', id: (x*7+i).to_s}}
                    = meal[:name]

                  .meal-info.text-center.top10
                    .avatar.meal-icon
                      = image_tag meal[:img_url], width: 53, height: 53, class: 'avatar'
                    %span
                      PHP
                      = meal[:price]
                  %div.input-group.input-group-sm.top10
                    %input.form-control{type: 'number', value: 1}
                    %span.input-group-addon servings
      .row
        .col-md-6
          Total:
          %span PHP 600.00
        .col-md-6
          = link_to 'Checkout', cart_path, class: 'btn btn-green btn-primary pull-right'

#searchMealModal.modal.fade{role: 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}} &times;
        %h4.modal-title Set Meal
      .modal-body
        .input-group
          %input.form-control{type: 'text', placeholder: 'Search Meal'}
          %span.input-group-addon
            %i.fa.fa-search
        - meals = random_meal(6)
        .list-group.top5
          - meals.each do |meal|
            %a.list-group-item{href: 'javascript:;', data: {dismiss: 'modal'}}
              .avatar.meal-icon
                = image_tag meal[:img_url], width: 53, height: 53, class: 'avatar'
              = meal[:name].to_s + ' - PHP ' + meal[:price].to_s

-#popover
.row#popoverTemplate.hide
  .header-section
    %h4#mealName
  %ul.nav.nav-tabs
    %li.clickable.active
      %a#ingredientsTab{data: {toggle: 'tab'}, href: '.ingredients'} Ingredients
    %li.clickable.nav-item
      %a#directionsTab{data: {toggle: 'tab'}, href: '.directions'} Directions
  .tab-content
    #ingredients.tab-pane.in.active.ingredients
      %ul.top5{style: 'list-style-type: circle'}
        %li 2 tablespoons extra-virgin olive oil
        %li 1 small onion, chopped
        %li 1 carrot, chopped
        %li 1 shallot, minced
        %li 3 1/2 ounces prosciutto, chopped
        %li 11 ounces ground pork
        %li 11 ounces ground beef
        %li 1 teaspoon ground nutmeg
        %li 1/2 teaspoon ground cinnamon
        %li salt to taste
    #directions.tab-pane.directions
      %ul.top5{style: 'list-style-type: circle'}
        %li Heat olive oil in a saucepan over medium heat; cook and stir onion, carrot, shallot, and prosciutto until onion is translucent and prosciutto releases some fat, about 10 minutes. Add pork and beef; season with 1 teaspoon nutmeg, cinnamon, and salt to taste. Cook and stir over medium-high heat until browned and crumbly, about 10 minutes.
        %li Pour red wine over meat mixture; increase heat and cook until wine evaporates, about 3 minutes. Add tomatoes and mix well; bring to a boil, cover, reduce heat, and simmer, stirring occasionally, until tomatoes break down and flavors of Bolognese sauce have combined, 1 1/2 to 2 hours.
        %li Melt butter in a saucepan over medium-low heat; add flour. Whisk vigorously until mixture is smooth. Pour in milk and cook, stirring occasionally, over medium heat until white sauce thickens enough to cover the back of a spoon, about 10 minutes; season with 1/2 teaspoon nutmeg, salt, and pepper.
        %li Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in the boiling water, stirring occasionally until tender yet firm to the bite, about 8 minutes. Drain and run under cold water to stop the cooking process. Lay noodles on a clean towel and pat dry.
        %li Pour a ladleful of Bolognese sauce and a ladleful of white sauce over the bottom of a 9x13-inch baking dish; top with 3 or 4 lasagna noodles. Cover noodles with 1/3 of the white sauce and 1/3 of the Bolognese sauce. Sprinkle some of the Parmesan cheese on top; cover with lasagna noodles. Repeat layers, ending with white sauce and Parmesan cheese.
        %li Bake in the preheated oven until bubbling and top is golden brown, 30 to 40 minutes. Let stand 3 to 4 minutes before slicing.

app/views/layouts/_cdn_assets.html.haml
- if use_cdn?
  -# JQUERY
  = javascript_include_tag jquery_cdn_url

  -# BOOTSTRAP
  = stylesheet_link_tag bootstrap_cdn_url('css'), bootstrap_css_settings
  = javascript_include_tag bootstrap_cdn_url('js'), bootstrap_js_settings
  = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'

  -#ANGULAR JS
  = javascript_include_tag angular_cdn_url


- else
  = javascript_include_tag 'cdn', 'data-turbolinks-track': 'reload'
  = stylesheet_link_tag 'cdn', media: 'all', 'data-turbolinks-track': 'reload'

app/views/layouts/_top_navigation_bar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top#header{role: 'navigation'}
  %div.container
    .navbar-header
      %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '#myNavbar'}}
        %span.icon-bar
        %span.icon-bar
          %span.icon-bar
      -#%a.clickable{class: 'brand'}
      = link_to '', root_path, class: 'brand'
    .collapse.navbar-collapse#myNavbar
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Services', '#services'
        %li= link_to 'How It Works', '#how'
        - if current_user
          %li= link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Log in', '#', data: {target: '#login', toggle: 'modal'}
          %li.btn-trial= link_to 'Become a Tig', '#', data: {target: '#signup', toggle: 'modal'}
          -#%li.btn-trial= link_to 'Become a TIG', '#'

app/views/layouts/application.html.haml
<!doctype html>
%html{lang: 'en'}
  %head
    %meta{:charset => "UTF-8"}
    %meta{:name => "viewport", :content =>"width=device-width, initial-scale=1.0"}
    = csrf_meta_tags
    %title Tabang

    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans', media: 'all', 'data-turbolinks-track': 'reload'
    = render 'layouts/cdn_assets'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = yield :head
    = yield :extra_css
  %body
    = render 'layouts/top_navigation_bar'
    = yield
    = yield :extra_javascripts

app/views/pages/_confirmation_modal.html.haml
.modal.fade#confirmation{role: 'dialog'}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'} &times;
        %h4.modal-title.text-center.form-title Tabang is on its Way!
      .modal-body.padtrbl
        .meal-info.text-center.top10
          .avatar.meal-icon-md
            = image_tag 'jhonny.png', width: 93, height: 93, class: 'avatar'
        #ratingWrapper
          #rating
            %ul#rating.tex-center
              - 5.times do
                %li.clickable
                  %i.fa.fa-star.fa-2x
        .text-center
          %h4
            Meet Juan dela Cruz
          .text-center.quote
            %p.small-text
              He will be the one to do cleaning in your home. You could communicate with him to give a much more specific job description.
        -#.row
          -#.banner-text.text-center
            -#.text-border
              -#%h2.text-dec
                -#Tabang is on its way!
            .intro-para.text-center.quote
              -#%p.big-text
                -#Book a top-rated handyman. From furniture assembly to TV mounting, we'll take care of your home maintenance needs.
              %p.small-text
                ETA: 5 mins
        .row
          .col-xs-12
            = link_to 'Contact', root_url, class: 'btn btn-green btn-block btn-flat'

app/views/pages/cart.html.haml
.wrapper#cartContent{ng: { controller: 'CartCtrl', init: 'init()' }}
  %section#form-section.section-padding
    .container
      .row
        .header-section.text-center
          %h2 Cart
      .row
        .table-responsive
          %table.table.table-bordered.table-striped.table-fixed
            %thead
              %tr
                %th Product
                %th Unit Price
                %th Quantity
                %th Total Price
                %th
            %tbody
              - ingredient_list.sample(5).each do |ingredient|
                %tr
                  %td
                    .avatar
                      = image_tag "ingredients/#{ingredient}.jpg", width: 53, height: 53, class: 'avatar'
                    %span
                      =ingredient
                  %td= 'PHP ' + rand(50..150).to_s + '/kg'
                  %td
                    %div.input-group.input-group-sm.top10
                      %input.form-control{type: 'number', value: 1}
                      %span.input-group-addon kg
                  %td
                    PHP 333
                  %td
                    %button.btn.btn-default
                      Remove 
      .row
        .col-md-6
          Total:
          %span PHP 600.00
        .col-md-6
          = link_to 'Checkout', location_path, class: 'btn btn-green btn-primary pull-right'

app/views/pages/location.html.haml
.wrapper{ng: { controller: 'LocationCtrl'}}
  %section#form-section.section-padding
    .container
      .row
        .header-section.text-center
          %h2 Where do you need help?
    .container
      .row
        #form-container
          %form#location-form.center-form
            #step-one.form-step
              .form-group
                %label Street Address
                %input.form-control{placeholder: 'Street Address'}
              .form-group
                %label Apt, Suite, Bldg. (optional)
                %input.form-control{placeholder: 'Apt, Suite, Bldg. (optional)'}
              .form-group
                %label City
                %select.form-control
                  %option Cebu
                  %option Lapu-Lapu
                  %option Mandaue
              .step-navigator
                %button.btn.btn-green.btn-flat.pull-right{'ng-click' => 'showFormTwo()'}
                  Next
            #step-two.form-step{style: 'display: none'}
              %div#map-container{'map-lazy-load' => 'https://maps.google.com/maps/api/js?key=AIzaSyCziK9432fcl47DuauH6xf1SyGh7s0U_1g'}
                .centerMarker
                %ng-map{center: '10.3157, 123.8854', zoom: '14'}
              %br
              %p
                Drag map to change location.
              %br
              .step-navigator
                %button.btn.btn-green.btn-flat.pull-left{'ng-click' => 'showFormOne()'}
                  Back
                = link_to 'Continue', task_details_path, class: 'btn btn-green btn-flat pull-right'